
package org.apereo.cas.support.sms.MagfaSDK;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * Magfa SOAP Server documentation
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MagfaSoapServer", targetNamespace = "webservice.magfa.com")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MagfaSoapServer {


    /**
     * Get new incoming messages, or of a short number if specified)
     * 
     * @param shortNumber
     * @param count
     * @return
     *     returns com.company.MessagesResult
     */
    @WebMethod
    @WebResult(partName = "return")
    public MessagesResult messages(
            @WebParam(name = "count", partName = "count")
                    int count,
            @WebParam(name = "shortNumber", partName = "shortNumber")
                    String shortNumber);

    /**
     * Get message-id of a user-id
     *
     * @param uid
     * @return
     *     returns com.company.MessageIdResult
     */
    @WebMethod
    @WebResult(partName = "return")
    public MessageIdResult mid(
            @WebParam(name = "uid", partName = "uid")
                    long uid);

    /**
     * Get message status (returns detailed status)
     *
     * @param mids
     * @return
     *     returns com.company.DeliveryResult
     */
    @WebMethod
    @WebResult(partName = "return")
    public DeliveryResult statuses(
            @WebParam(name = "mids", partName = "mids")
                    LongArray mids);

    /**
     * Send message
     *
     * @param priorities
     * @param uids
     * @param recipients
     * @param encodings
     * @param messages
     * @param udhs
     * @param senders
     * @return
     *     returns com.company.SendResult
     */
    @WebMethod
    @WebResult(partName = "return")
    public SendResult send(
            @WebParam(name = "messages", partName = "messages")
                    StringArray messages,
            @WebParam(name = "senders", partName = "senders")
                    StringArray senders,
            @WebParam(name = "recipients", partName = "recipients")
                    StringArray recipients,
            @WebParam(name = "uids", partName = "uids")
                    LongArray uids,
            @WebParam(name = "encodings", partName = "encodings")
                    IntArray encodings,
            @WebParam(name = "udhs", partName = "udhs")
                    StringArray udhs,
            @WebParam(name = "priorities", partName = "priorities")
                    IntArray priorities);

    /**
     * Get account balance
     * 
     * @return
     *     returns com.company.CreditResult
     */
    @WebMethod
    @WebResult(partName = "return")
    public CreditResult balance();

}
